### PR TITLE
Use fork to run the script

### LINKED ISSUE #4: Pages not always regenerated
I am using this repo for the Thot docs site but I found that the webpage is not always updated to the latest version of the generated JS.

In order to fix that, I use this `runScript`:

```fs
function runScript(scriptPath) {
    try {
        console.log("Running script")
        var childProcess = require("child_process");
        var path = require("path");
        var cp = childProcess.fork(scriptPath);
        cp.on("exit", function (code, signal) {
            if (code === 0) {
                console.log("Success");
            } else {
                console.log("Exit", { code: code, signal: signal });
            }
        });
        cp.on("error", console.error.bind(console));
    } catch (err) {
        console.error(err);
    }
}
```

Should we update the repo with it ?

### PR DESCRIPTION
**Pull request by MangelMaxime**
Fix #4 

Changes:
- Use fork to run the script
- Detect production/development env useful to make the URL conditionals ([example](https://github.com/MangelMaxime/Thot/blob/master/docs/src/Route.fs#L4-L8))

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks! BTW, what's the difference between using `/` for the host vs the full URL?

**Comment by MangelMaxime** [comment]
I am using `/` in dev mode. And benefit of using `/` instead of `http://localhost:8080/` is if I decide to host the server on port `8081` then this would work without any change because the browser pick the host part from url bar directly. It's useful, as I generally work on several project at the same time :)

**Comment by alfonsogarciacaro** [comment]
Ah, ok. I see now you are using "https://mangelmaxime.github.io/Thot/" in the sample, that's why you cannot use `/` in production :)

**Comment by MangelMaxime** [comment]
Yes, because most of the gh-pages are not hosted at the root of the "subdomain".

But having the env/prod options make it work like a charm so no problem :)

**Pull request merged**
