### PR TITLE
Start to include Fulma

### PR DESCRIPTION
**Pull request by MangelMaxime**
@alfonsogarciacaro I tried to add Fulma but I got an error when building the project with Fable. If I build it with `dotnet build` the build is passing.

Fable say:

```
C:\Users\mange\Workspace\Github\fable-compiler\static-page-generator\src\Main.fs(12,5): (12,10) error FSHARP: The namespace or module 'Fulma' is not defined.
C:\Users\mange\Workspace\Github\fable-compiler\static-page-generator\src\Main.fs(41,8): (41,13) error FSHARP: The value, namespace, type or module 'Table' is not defined. Maybe you want one of the following:
   table
   TableLayout
   Fable
   TabSize
   Label
```

I added the `reload` package to package.json.
Also, the paket.exe was telling me that's it was not working on my version of Windows... So I repushed it..

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Ah, damn! Forgot about that, right now Fable is using `Fable.` prefix to distinguish Fable libraries, and Fulma doesn't have it now. Hmmm, not sure what's the best thing to do here. Easiest solution right now is to add the `Fable.` prefix to Fulma (at least for the package), but I guess we should find another way to identify Fable libraries 🤔 

BTW, why package-lock.json is changing so much. Is it because OS-specific modules? What npm version are you using? I have 5.3.0.

**Comment by alfonsogarciacaro** [comment]
Ok, don't worry about renaming Fulma, I'll find another way ;)

**Comment by MangelMaxime** [comment]
I am also on npm 5.3.0 with node 8.1.0

And I find it strange too that I have all this change in the packge-lock.json... I am under windows that probably the difference ?

Ok, will wait patiently for your solution so :D

**Comment by alfonsogarciacaro** [comment]
Ok, I've published Fable 1.2.0-beta-003, could you please download latest changes and try again? I also had problems with `paket.exe` so I copied it from Fable repo.

**Comment by MangelMaxime** [comment]
Seems like it's not our day with paket :)

I will give it a try.

**Comment by MangelMaxime** [comment]
Ok it works now with my little fix. 

Thanks you 👏 👏

**Pull request merged**
